version: "3.8"

services:
  nodejs:
    container_name: nodejs_puppeteer_server
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "${PWD}/:/app/"
    networks:
      - puppeteer-network
    entrypoint: ["npm", "start"]

networks:
  puppeteer-network:
    name: puppeteer-network
